name: Create ZIP files

on:
  release:
    types: [published]

jobs:
  zip:
    name: Create ZIP files and add it to last release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir zip
        
      - name: Create ZIP files
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./zip/archive.zip ./loader.php ./modules

      - name: Upload files to release
        uses: danyadev/upload-to-release@master
        with:
          files: |
            [./zip/archive.zip, senses.zip, application/zip]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
